name: Lint

on:
  pull_request:
    types:
      - opened
    branches:
      - master
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install
        run: npm ci
      - name: Run eslint
        run: npm run lint
